import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import { createServer as createViteServer } from 'vite';
import { GoogleGenAI } from '@google/genai';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Initialize Gemini AI client lazily if key is provided
  const getGeminiClient = () => {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey === 'MY_GEMINI_API_KEY') {
      return null;
    }
    return new GoogleGenAI({ apiKey });
  };

  // Agent execution endpoint
  app.post('/api/agent/execute', async (req, res) => {
    try {
      const { agentRole, agentName, prompt, taskType } = req.body;
      const ai = getGeminiClient();

      if (ai) {
        const systemInstruction = `You are ${agentName}, an autonomous AI agent with role: ${agentRole}. 
You operate inside a developer-grade Linux terminal environment.
Provide a structured output with step-by-step reasoning logs, generated artifact code, and transparency breakdown.`;

        const response = await ai.models.generateContent({
          model: 'gemini-2.5-flash',
          contents: `Task Directive: ${prompt}\n\nPlease generate response formatted as JSON:
{
  "logs": ["log 1", "log 2", "log 3"],
  "reasoningExplanation": "Detailed rationale",
  "transparency": {
    "whatHappened": "Summary",
    "whyItHappened": "Reasoning",
    "confidenceScore": 98.5
  },
  "codeArtifact": {
    "filename": "output_artifact.ext",
    "language": "typescript",
    "code": "// Code content"
  }
}`,
          config: {
            systemInstruction,
            responseMimeType: 'application/json',
          },
        });

        const jsonText = response.text || '{}';
        const parsed = JSON.parse(jsonText);
        return res.json({ success: true, source: 'gemini-2.5-flash', result: parsed });
      }

      // Fallback response generator if key not set
      const timestamp = new Date().toLocaleTimeString('en-US', { hour12: false });
      return res.json({
        success: true,
        source: 'simulated-kernel',
        result: {
          logs: [
            `[${timestamp}] Initiating command directive for ${agentName}...`,
            `[${timestamp}] Parsing context parameters for role: ${agentRole}...`,
            `[${timestamp}] Executing sub-routine: "${prompt.slice(0, 40)}..."`,
            `[${timestamp}] Command execution successful. 0 errors logged.`,
          ],
          reasoningExplanation: `Executed task: "${prompt}". Analyzed dependency graph and updated local vector memory buffer.`,
          transparency: {
            whatHappened: `Completed terminal execution for directive: "${prompt}"`,
            whyItHappened: `User manual prompt injection into ${agentName} terminal interface.`,
            confidenceScore: 97.8,
          },
          codeArtifact: {
            filename: `/workspace/output_${agentRole.toLowerCase()}.ts`,
            language: 'typescript',
            code: `// Output generated by ${agentName} (${agentRole})\n// Directive: ${prompt}\nexport const result = {\n  status: "COMPLETED",\n  timestamp: "${timestamp}"\n};`,
          },
        },
      });
    } catch (err: any) {
      console.error('Error executing agent directive:', err);
      return res.status(500).json({ error: err.message || 'Execution failed' });
    }
  });

  // Health check API
  app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', uptime: process.uptime(), time: new Date().toISOString() });
  });

  // Vite development middleware
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`AgentOS Kernel Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
